### ISSUE TITLE
RR-docker

### ISSUE THREAD

**Issue by bhack** [qiuwch/unrealcv-packaging#1]
What are the differences between this and https://github.com/qiuwch/unrealcv-docker-images?
And what is this image https://hub.docker.com/r/qiuwch/rr/?

**Comment by qiuwch** [comment]
This dockerhub image is something  I am testing, it will be used for our reinforcement learning task. The docker-image repo contains Docker image, this repo contains packaging script. All these stuffs are onging progress and has not been well documented yet.
